name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: sudo apt-get update && sudo apt install libdbus-1-dev pkg-config
      - name: Install Rust 1.65 and 1.69
        run: rustup set profile default && rustup default 1.65.0 && rustup toolchain install 1.69
      - name: Check code formatting
        run: cargo +1.69 fmt -- --check
      - name: Build
        run: cargo build --examples --bins --all-features --quiet
      - name: Build documentation
        run: cargo doc --no-deps --quiet
      - name: Code analysis
        run: cargo clippy --all-features --quiet
      - name: Run tests (debug)
        run: cargo test --quiet
      - name: Run tests (release)
        run: cargo test --release --quiet
      - name: Run agg-speed
        run: |
          cargo build --quiet --release --bin agg-speed
          RUST_LOG=info cargo run --quiet --release --bin agg-speed -- server --tls --no-monitor --oneshot &
          sleep 1
          RUST_LOG=info cargo run --quiet --release --bin agg-speed -- client --tls --no-monitor --time 15 --tcp localhost
